[project]
name = "ai-squad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "redis>=7.1.0",
    "scikit-learn>=1.7.2",
    "sentence-transformers>=5.1.2",
]
